# tasks file for phpredis
---
- name: install dependencies
  apt:
    name: "{{ phpredis_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - phpredis
    - phpredis-dependencies

- name: create (checkout) directory
  file:
    path: /var/lib/ansible/phpredis/checkouts
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - phpredis
    - phpredis-checkout

- name: checkout repository
  git:
    repo: https://github.com/phpredis/phpredis.git
    dest: "/var/lib/ansible/phpredis/checkouts/phpredis"
    version: "{{ phpredis_version }}"
    force: true
  tags:
    - configuration
    - phpredis
    - phpredis-checkout

- name: build deb file
  shell: >
    /var/lib/ansible/phpredis/checkouts/phpredis/mkdeb.sh &&
    mv /var/lib/ansible/phpredis/checkouts/phpredis/$(ls -t phpredis-*.deb | head -1) /var/lib/ansible/phpredis/checkouts/phpredis-{{ phpredis_version }}_{{ ansible_machine }}.deb
  args:
    chdir: "/var/lib/ansible/phpredis/checkouts/phpredis"
    creates: "/var/lib/ansible/phpredis/checkouts/phpredis-{{ phpredis_version }}_{{ ansible_machine }}.deb"
  register: _result
  tags:
    - configuration
    - phpredis
    - phpredis-build-deb

- name: install deb file
  apt:
    deb: "/var/lib/ansible/phpredis/checkouts/phpredis-{{ phpredis_version }}_{{ ansible_machine }}.deb"
  tags:
    - configuration
    - phpredis
    - phpredis-install-deb

- name: cleanup build
  shell: >
    git reset --hard && git clean -d -x -f
  args:
    chdir: "/var/lib/ansible/phpredis/checkouts/phpredis"
  when: _result is changed
  tags:
    - configuration
    - phpredis
    - phpredis-cleanup-build
